# Generated by Django 3.2 on 2021-05-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questtion',
            new_name='Question',
        ),
    ]
